services:
  api:
    extends:
      service: api
      file: docker-compose.yml
    volumes:
      - ./service:/app/service # Mount service directory for live code changes
      - ./backups:/app/backups # Mount backups directory for enrichment CSVs
    environment:
      DEBUG: "true" # Enable debug for local development
      SMTP_SERVER: "mailhog" # Point to MailHog service
      SMTP_PORT: "1025" # MailHog's SMTP port
    command: [ "sh", "-c", "python service/db/migrate.py && python -m uvicorn service.main:app --host 0.0.0.0 --port 8000 --reload" ] # Enable --reload
    logging:
      # Add this section
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  crawler:
    container_name: pricemice-crawler-1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      # DB_DSN is now defined directly in .env
      PYTHONUTF8: "1"
      API_KEY: ${API_KEY}
      BASE_URL: ${BASE_URL}
    depends_on:
      - db
    volumes:
      - ./crawler_output:/app/output # Mount crawler output for direct access
      - .:/app # Mount the entire project directory
    command: [ "tail", "-f", "/dev/null" ]

  pgadmin:
    extends:
      service: pgadmin
      file: docker-compose.yml
    environment:
      # --- ADD THESE TWO LINES ---
      # This disables the "Set Master Password" prompt on first launch.
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      # This disables the user login screen entirely.
      PGADMIN_CONFIG_AUTHENTICATION_SOURCES: "[]"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80" # Expose PGAdmin port for local access
    volumes:
      - ./pgadmin/servers_dev.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgadmin4/pgpass
    # This command is still essential to fix the pgpass file permissions.

  mailhog:
    container_name: pricemice-mailhog-1
    # Add MailHog service
    image: mailhog/mailhog
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  pgadmin_data: {}
  db_data: {}
  db_backups: {}
