services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      REDIRECT_URL: http://localhost:8000/docs
      PYTHONUTF8: "1"
    volumes:
      - ./.env:/app/.env
      - ./crawler_output:/app/crawler_output # Mount crawler output for direct access
      - .:/app # Mount the entire project directory
    command: [ "sh", "-c", "python -m uvicorn service.main:app --host 0.0.0.0 --port 8000 --reload" ] # Add --reload for development

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      PYTHONUTF8: "1"
    volumes:
      - ./crawler_output:/app/output # Mount crawler output for direct access
      - .:/app # Mount the entire project directory
    command: [ "tail", "-f", "/dev/null" ]
