# ===================================================================
# DOCKER-COMPOSE - PRODUCTION OVERRIDE
# ===================================================================
# This file OVERRIDES the base docker-compose.yml for production.
# It should be used like this:
#   docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# ===================================================================

version: '3.8'

services:
  db:
    image: ghcr.io/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME/db:${IMAGE_TAG:-latest}
    build: null

  api:
    image: ghcr.io/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME/api:${IMAGE_TAG:-latest}
    build: null
    volumes:
      - ./.env:/app/.env
      - ./crawler_output:/app/crawler_output
    command: [ "sh", "-c", "python -m uvicorn service.main:app --host 0.0.0.0 --port 8000" ]

  alloy:
    image: ghcr.io/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME/alloy:${IMAGE_TAG:-latest}
    build: null
