# ===================================================================
# DOCKER-COMPOSE - PRODUCTION OVERRIDE
# ===================================================================
# This file OVERRIDES the base docker-compose.yml for production.
# It should be used like this:
#   docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# ===================================================================

services:
  db:
    image: ghcr.io/dmiric/cijene-api/db:latest
    build: null

  api:
    image: ghcr.io/dmiric/cijene-api/api:latest
    build: null
    volumes:
      - ./.env:/app/.env
      - ./crawler_output:/app/crawler_output
    command: [ "sh", "-c", "python -m uvicorn service.main:app --host 0.0.0.0 --port 8000" ]

  node_exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.9.1
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring-network
