# ===================================================================
# DOCKER-COMPOSE - PRODUCTION OVERRIDE
# ===================================================================
# This file OVERRIDES the base docker-compose.yml for production.
# It should be used like this:
#   docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# ===================================================================

services:
  db:
    image: ghcr.io/${LOWER_IMAGE_OWNER}/${LOWER_REPO_NAME}/db:${IMAGE_TAG:-latest}
    build: null
    command: >
      bash -c "
        until pg_isready -h localhost -p 5432 -U $$POSTGRES_USER; do
          echo 'Waiting for PostgreSQL to be ready...'
          sleep 2
        done;
        psql -v ON_ERROR_STOP=1 --username \"$$POSTGRES_USER\" --dbname \"$$POSTGRES_DB\" -c 'CREATE EXTENSION IF NOT EXISTS vector;';
        # Keep the container running indefinitely
        tail -f /dev/null
      "

  api:
    image: ghcr.io/${LOWER_IMAGE_OWNER}/${LOWER_REPO_NAME}/api:${IMAGE_TAG:-latest}
    build: null
    volumes:
      - ./.env:/app/.env
      - ./crawler_output:/app/crawler_output
    command: [ "sh", "-c", "python -m uvicorn service.main:app --host 0.0.0.0 --port 8000" ]

  alloy:
    image: ghcr.io/${LOWER_IMAGE_OWNER}/${LOWER_REPO_NAME}/alloy:${IMAGE_TAG:-latest}
    build: null
