version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cijene_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./service/db/psql.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432" # Optional: Expose DB port for local access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cijene_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_DSN: postgresql://user:password@db:5432/cijene_db
      REDIRECT_URL: http://localhost:8000/docs # Example, adjust as needed
      DEBUG: "true"
      PYTHONUTF8: "1"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - crawler_data:/app/crawler_output # Mount shared volume for import
    command: ["python", "-m", "service.wait_for_db"]

  crawler:
    build: .
    environment:
      DB_DSN: postgresql://user:password@db:5432/cijene_db
      DEBUG: "true"
      PYTHONUTF8: "1"
    depends_on:
      - db
    volumes:
      - crawler_data:/app/output # Crawler writes to this shared volume
    # This service is not meant to be continuously running.
    # It's here to provide a container for running crawler commands.
    # Example usage: docker-compose run --rm crawler python -m crawler.cli.crawl /app/output --date 2024-01-01
    command: ["tail", "-f", "/dev/null"] # Keep container alive for manual execution

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
  crawler_data: # New volume for crawler output
