services:
  db:
    container_name: pricemice-db-1
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: postgis/postgis:16-3.4
    ports:
      - "0.0.0.0:5432:5432"
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./service/db/psql.sql:/docker-entrypoint-initdb.d/init.sql # Commented out to prevent automatic schema creation on startup
      - ./docker/db/init-croatian-fts.sh:/docker-entrypoint-initdb.d/init-croatian-fts.sh
      - ./docker/db/croatian.stop:/usr/share/postgresql/16/tsearch_data/croatian.stop
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: pricemice-api-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      # DB_DSN is now defined directly in .env
      REDIRECT_URL: http://localhost:8000/docs
      PYTHONUTF8: "1"
      PROMETHEUS_PUSHGATEWAY_URL: http://pushgateway:9091 # Added Pushgateway URL
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
      - ./crawler_output:/app/crawler_output # Mount crawler output for direct access
      - .:/app # Mount the entire project directory
    command: [ "sh", "-c", "python -m uvicorn service.main:app --host 0.0.0.0 --port 8000 --reload" ] # Add --reload for development

  crawler:
    container_name: pricemice-crawler-1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      # DB_DSN is now defined directly in .env
      PYTHONUTF8: "1"
      API_KEY: ${API_KEY}
      BASE_URL: ${BASE_URL}
    depends_on:
      - db
    volumes:
      - ./crawler_output:/app/output # Mount crawler output for direct access
      - .:/app # Mount the entire project directory
    command: [ "tail", "-f", "/dev/null" ]

  pgadmin:
    container_name: pricemice-pgadmin-1
    image: dpage/pgadmin4
    env_file:
      - ./.env
    environment:
      # This disables the "Set Master Password" prompt on first launch.
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      # This disables the user login screen entirely.
      PGADMIN_CONFIG_AUTHENTICATION_SOURCES: "[]"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    depends_on:
      - db
    ports:
      - "127.0.0.1:80:80" # Expose pgAdmin to the host's loopback interface
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - db_backups:/var/lib/pgadmin/backups
      - ./pgadmin/preferences.json:/pgadmin4/preferences.json

  backup:
    container_name: pricemice-backup-1
    image: postgis/postgis:16-3.4
    env_file:
      - ./.env
    volumes:
      - db_backups:/backups
      - ./scripts:/scripts
    depends_on:
      db:
        condition: service_healthy
    command: [ "tail", "-f", "/dev/null" ]

  pushgateway:
    # Added Pushgateway service
    container_name: pricemice-pushgateway-1
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"
    command:
      - '--web.listen-address=:9091'

  prometheus:
    container_name: pricemice-prometheus-1
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - api
      - pushgateway # Added dependency on pushgateway

  grafana:
    container_name: pricemice-grafana-1
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_SECURITY_ADMIN_USER: "${GRAFANA_ADMIN_USER}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}"
    depends_on:
      - prometheus

volumes:
  db_data:
  pgadmin_data:
  db_backups:
