# ./Taskfile.yml
version: '3'

# Automatically load variables from the .env file. This replaces 'include .env'.
dotenv: ['.env']

# Global variables available to ALL included tasks.
vars:
  # Values from .env are already loaded, but you can define defaults here
  # for variables that might not be in .env.
  IMAGE_OWNER: dmiric
  REPO_NAME: cijene-api
  EXCLUDE_VOLUMES: 'cijene-api-clone_crawler_data,cijene-api-clone_pgadmin_data'
  QUERY: limun
  NUM_WORKERS: 1
  BATCH_SIZE: 50
  DATE: '{{now | date "20060102"}}'
  DOCKER_BUILD_LOG_FILE: 'logs/docker-build.log'

# Include the other task files and assign them a namespace.
includes:
  rebuild: ./tasks/rebuild.yml
  data: ./tasks/data.yml
  db: ./tasks/db.yml
  test: ./tasks/test.yml
  remote: ./tasks/remote.yml
  logs: ./tasks/logs.yml
  git: ./tasks/git.yml

tasks:
  default:
    desc: 'Lists all available tasks from all included files.'
    cmds:
      # CORRECT - This runs the command "task --list" in the shell
      - task --list
    silent: true
