apiVersion: 1
groups:
    - orgId: 1
      name: Evaluation group 3
      folder: Hetzner Worker
      interval: 3m
      rules:
        - uid: beu3v69uqje2oc
          title: Hetzner Worker Creation Failed
          condition: C
          data:
            - refId: A
              queryType: range
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: P8E80F9AEF21F6940
              model:
                datasource:
                    type: loki
                    uid: P8E80F9AEF21F6940
                editorMode: code
                expr: 'count_over_time({container=~"hetzner-worker-container.*"} |= `ERROR: Action ''create_server''` [5m])'
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: range
                refId: A
            - refId: reducer
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: reducer
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: reducer
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 3m
          annotations:
            description: Hetzner Worker Creation Failed
            summary: Hetzner Worker Creation Failed
          labels: {}
          isPaused: false
