{
 "title": "Dash 1",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "API Logs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (\r\n  count_over_time(\r\n    {job=\"api\"} | json | __error__=\"\" | level != \"\" [$__interval]\r\n  )\r\n)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint, method, status_code) (label_replace(http_requests_total{status_code=~\"[45]..\"}, \"endpoint\", \"$1*/items\", \"endpoint\", \"^(/.*/shopping_lists/)[^/]+(/items.*)$\"))",
     "legendFormat": "{{endpoint}} ({{method}}) - {{status_code}}"
    }
   ]
  },
  {
   "title": "API",
   "type": "logs",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"api\"}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "sum by (endpoint, method, status_code) (http_requests_total{status_code=~\"[23]..\"})",
     "legendFormat": "{{endpoint}} ({{method}}) - {{status_code}}"
    }
   ]
  },
  {
   "title": "Golden record processing",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(golden_records_processed_total{}[$__rate_interval]))",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  }
 ]
}