apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    features:
      - tracing
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderValue1: "anonymous"
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
    readOnly: false
