# =================================================================
# FINAL - COMBINED FIX CONFIGURATION
# =================================================================

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-file-scrape
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/lib/docker/containers/*/*-json.log
          job: docker-logs

    pipeline_stages:
      # Stage 1: Use the 'docker' stage to correctly parse the file format.
      - docker: {}

      # Stage 2: Parse the now-clean log line as logfmt.
      - logfmt:
          # ADDING THIS MAPPING KEY BACK IN to satisfy the startup error.
          # An empty map should work, but we will use a real one to be safe.
          mapping:
             msg:

      # Stage 3: Create a 'level' label from the parsed logfmt data.
      - labels:
          level:

    relabel_configs:
      # This section extracts the Container ID from the filename.
      - source_labels: [__path__]
        # This regex captures the 64-character hex ID from the file path.
        regex: '.*/([0-9a-f]{64})-json\\.log'
        target_label: container_id