# Use a Python base image
FROM python:3.10-slim-buster

# Set the working directory inside the container
WORKDIR /app

# Copy requirements.txt from the vps_workers directory
COPY vps_workers/requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the worker script
COPY vps_workers/hetzner_worker.py .

# Command to run the script when the container starts
CMD ["python", "hetzner_worker.py"]
