name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - '.clinerules/**'

# Use environment variables to keep image names consistent and DRY
env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  # Convert owner and repo name to lowercase for Docker image tags

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.IMAGE_OWNER }}
        password: ${{ secrets.CR_TOKEN }}

    # ===================================================================
    # Build and push each custom service as a separate image
    # ===================================================================

    - name: Build and Push API Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile # Dockerfile for the API
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.REPO_NAME }}/api:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.REPO_NAME }}/api:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and Push DB Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.postgres # Dockerfile for the DB
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.REPO_NAME }}/db:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.REPO_NAME }}/db:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and Push Alloy Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.alloy # Dockerfile for Alloy
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.REPO_NAME }}/alloy:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.REPO_NAME }}/alloy:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # ===================================================================
    # CONSOLIDATED SECTION: Configure server in a single, efficient step
    # ===================================================================
    - name: Configure Server (Timezone, Swap, and Cron Jobs)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # --- Set Server Timezone ---
          #### This code won't run because of the sudo, but it's here as a reminder
          echo "--> Configuring server time and NTP synchronization..."
          sudo timedatectl set-timezone UTC
          sudo timedatectl set-ntp true
          
          # --- Configure Swap Space ---
          #### This code won't run because of the sudo, but it's here as a reminder
          echo "--> Checking/Configuring swap space..."
          if ! grep -q "swapfile" /proc/swaps; then
            sudo fallocate -l 4G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
            echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf
            echo 'vm.vfs_cache_pressure=50' | sudo tee -a /etc/sysctl.conf
            echo "Swap space configured."
          else
            echo "Swap space already configured."
          fi

          # --- Configure Cron Jobs ---
          echo "--> Configuring cron jobs..."
          # Hetzner Worker (New - Docker manages logs)
          (crontab -l 2>/dev/null | grep -v 'hetzner-worker') | crontab -
          (crontab -l 2>/dev/null; echo "0 6-11 * * * cd /home/dmiric/pricemice && docker run --rm --name hetzner-worker --log-driver=loki --log-opt loki-url="http://127.0.0.1:3100/loki/api/v1/push" --log-opt loki-external-labels="container=hetzner-worker,job=worker" --network=pricemice_monitoring-network -v "$(pwd)/.env:/app/.env:ro" -v "/home/dmiric/.ssh/pricemice-worker-key:/app/ssh_key:ro" -e SSH_KEY_PATH=/app/ssh_key hetzner-worker-image python hetzner_worker.py") | crontab -
          
          # Golden Record Orchestrator (New - Docker manages logs)
          (crontab -l 2>/dev/null | grep -v 'golden-record') | crontab -
          (crontab -l 2>/dev/null; echo "30 * * * * cd /home/dmiric/pricemice && docker compose -f docker-compose.yml -f docker-compose.prod.yml run --rm --name golden-record api python -m service.normaliser.golden_record.orchestrator_golden_records --normalizer-type grok --embedder-type gemini --num-workers 2 --batch-size 200") | crontab -
          
          # Price Calculation (New - Docker manages logs)
          (crontab -l 2>/dev/null | grep -v 'calc-prices') | crontab -
          (crontab -l 2>/dev/null; echo "50 * * * * cd /home/dmiric/pricemice && docker compose -f docker-compose.yml -f docker-compose.prod.yml run --rm --name calc-prices --env api python -m service.normaliser.orchestrator_prices --num-workers 1 --batch-size 10000") | crontab -
          
          echo "All cron jobs configured."

    # ===================================================================
    # REPLACED SECTION: Deploy using pre-built images and override file
    # ===================================================================
    - name: Deploy Application with Pre-built Images
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "--> Starting deployment..."
          cd ${{ secrets.APP_PATH }}
          
          echo "--> Pulling latest compose files from git..."
          git pull origin main

          echo "--> Logging into GitHub Container Registry..."
          echo ${{ secrets.CR_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ env.IMAGE_OWNER }} --password-stdin
          
          echo "--> Setting image tag for this deployment..."
          export IMAGE_TAG=${{ github.sha }}
          export LOWER_IMAGE_OWNER=$(echo "${{ env.IMAGE_OWNER }}" | tr '[:upper:]' '[:lower:]')
          export LOWER_REPO_NAME=$(echo "${{ env.REPO_NAME }}" | tr '[:upper:]' '[:lower:]')

          echo "--> Pulling new container images: ${{ env.IMAGE_TAG }}"
          docker compose -f docker-compose.yml -f docker-compose.prod.yml pull

          echo "--> Restarting services with new images..."
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --remove-orphans

          echo "--> Applying database migrations..."
          docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T api python service/db/migrate.py

          echo "--> Cleaning up old Docker images..."
          docker image prune -af
          
          echo "--> Cleaning up old Docker images..."
          docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions

          echo "--> Deployment successful!"
