apiVersion: 1

policies:
  - orgId: 1
    receiver: 'Primary Email Alerts'
    group_by: [alertname]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 0s
    match:
      alertname: Hetzner Worker Scheduled Job Not Detected
