apiVersion: 1
policies:
    - orgId: 1
      receiver: Primary Contact
      group_by:
        - grafana_folder
        - alertname
      routes:
        - receiver: Primary Contact
          object_matchers:
            - - notification_schedule
              - =
              - hetzner_worker_hours
          active_time_intervals:
            - Hetzner Worker Alert Working Times
          group_wait: 1m
          repeat_interval: 1h
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h